import React from 'react'
import { useNavigate } from 'react-router-dom'
export default function Page2() {

  // to navigate to page1 on clicking back button
  const navigate=useNavigate();
  return (
    <div >
      <h2>Page 2</h2>
      <section className='news'>
        <h3>Indian defence sector scales newer heights with latest technology</h3>
        <p className='para'>
        Indian defence sector is bolder than before and with every passing day it is arming itself to combat any kind of situation whereby providing stability to the country.
        The Indian Army is planning to procure approximate quantity 800 Light Armoured Multipurpose Vehicle (LAMV) for Mechanised Infantry and Armoured Corps. The LAMV is planned to be procured in sync with 'Make in India' and 'Atmanirbhar Bharat' initiative.
        The Request for Information generated by the Defence Ministry stated the LAMV will be employed by Reconnaissance (Recce) & Surveillance Platoons of Mechanised Infantry and Recce Troops of Armoured Corps for Recce & Surveillance tas ..
        </p>
      </section>
      <div className='containerFooter'>
      <button  onClick={()=>navigate('/')}>Back </button>
    </div>
    </div>
  )
}
